[package]
name = "remind-me"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.18", features = ["derive"] }
comfy-table = "7.1.1"
directories = "5.0.1"
inquire = "0.7.5"
rusqlite = { version = "0.32.1", features = ["chrono"] }
